### ISSUE TITLE
Fullstack: BoardPage

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/simply-name.it#74]
## User story

**Who:** **As a** User
**What:** **I want to** be able see the Board Page 
**Why:** **so that I can**  see the candidates that decide as an owner and I should also be able rank the candidates in a different order if I am an owner or a member. I will also want to be able to check the results by clicking on the Result button and accessing the Menu on the header of the page and see the options according to my user(owner or member). And finally to access the Members Modal View where all the members should be listed.

## Acceptance criteria

The page should look like this if the user is the Owner of the Board
<img width="470" alt="Screenshot 2021-07-30 at 13 53 02" src="https://user-images.githubusercontent.com/6642037/127649173-86270ffa-c737-43f8-bca9-6db45f7a912b.png">

The page should look like this if the user is the Member of the Board
<img width="461" alt="Screenshot 2021-07-30 at 13 52 22" src="https://user-images.githubusercontent.com/6642037/127649590-36808209-dfe2-4702-bf4b-0ac2f707492a.png">

The page should look like this either for the Owner or Member of the Board when the deadline is past due.
<img width="184" alt="Screenshot 2021-07-30 at 13 53 10" src="https://user-images.githubusercontent.com/6642037/127649668-81443405-715f-4e09-9d65-660f55431c8c.png">

When clicking on the Members button we should be able to call the Modal view and list all the members like shown below
<img width="135" alt="Screenshot 2021-07-30 at 14 13 48" src="https://user-images.githubusercontent.com/6642037/127651410-56bb2936-6dff-4fd8-bd66-4a5ad51136aa.png"><img width="123" alt="Screenshot 2021-07-30 at 14 13 18" src="https://user-images.githubusercontent.com/6642037/127651418-b16e93e9-3b78-49c6-b299-c52b79055ea9.png">

#### -> React Containers and Components 
- [x] Dummy Page - https://github.com/HackYourFuture-CPH/simply-name.it/issues/44
    1. [ ] BoardPage - src/client/containers/BoardPage/BoardPage.Container.js
    2. [ ] BoardPage - src/client/containers/BoardPage/BoardPage.Style.css
- [x] Header - https://github.com/HackYourFuture-CPH/simply-name.it/issues/15
- [x] Images - https://github.com/HackYourFuture-CPH/simply-name.it/pull/72
- [x] Title
- [x] Button - https://github.com/HackYourFuture-CPH/simply-name.it/issues/2
- [x] Input - https://github.com/HackYourFuture-CPH/simply-name.it/issues/9         
- [x] Button -  https://github.com/HackYourFuture-CPH/simply-name.it/issues/2 (probably needs some adaptation)
- [x] Card and List of Cards - https://github.com/HackYourFuture-CPH/simply-name.it/issues/18
- [x] Button -  https://github.com/HackYourFuture-CPH/simply-name.it/issues/2

#### -> Endpoints
- [x] Endpoint to update the ballots table - https://github.com/HackYourFuture-CPH/simply-name.it/issues/57
- [x] Endpoint to retrieve the result of a certain board - https://github.com/HackYourFuture-CPH/simply-name.it/issues/54
- [x] Endpoint to retrieve the list of all the members and owner of a specific board - https://github.com/HackYourFuture-CPH/simply-name.it/issues/75
- [x] Endpoint to get all the candidates from a board - https://github.com/HackYourFuture-CPH/simply-name.it/issues/64
