### ISSUE TITLE
Fullstack: ResultPage

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/simply-name.it#76]
## User story

**Who:** **As a** User
**What:** **I want to** be able see the Result Page 
**Why:** **so that I can**  can see what is the final decision regarding my topic/board

## Acceptance criteria

The Result Page should look like this:
<img width="279" alt="Screenshot 2021-07-30 at 18 00 21" src="https://user-images.githubusercontent.com/6642037/127680117-e24e99fa-cf4c-42d4-8414-8fad21ddfa6f.png">

#### -> React Containers and Components

- [x] Dummy Page - https://github.com/HackYourFuture-CPH/simply-name.it/issues/44
    - [ ] ResultPage - src/client/containers/ResultPage/ResultPage.Container.js
    - [ ] ResultPage - src/client/containers/ResultPage/ResultPage.Style.css
- [x] Arrow Button - https://github.com/HackYourFuture-CPH/simply-name.it/issues/4 (it should link to ProfilePage)
- [ ] Title
- [x] Confetti animation - https://github.com/HackYourFuture-CPH/simply-name.it/issues/13
- [ ] List of Cards - https://github.com/HackYourFuture-CPH/simply-name.it/issues/18

#### -> Endpoints
- [x] Endpoint to retrieve the result of a certain board - https://github.com/HackYourFuture-CPH/simply-name.it/issues/54

#### Backend

- [ ] Schedule result creation https://github.com/HackYourFuture-CPH/simply-name.it/issues/153
