### ISSUE TITLE
Fullstack: AddMemberPage

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/simply-name.it#81]
## User story

**Who:** **As a** User Owner of a Board
**What:** **I want to**  able to be open AddMembersPage
**Why:** **so that I can**  search for an existing member and add it to my Board

## Acceptance criteria

The page should look like the one below:
<img width="219" alt="Screenshot 2021-07-30 at 16 25 03" src="https://user-images.githubusercontent.com/6642037/127667567-c816842d-a13c-4255-b73d-5026dc1b7661.png">

#### -> React Containers and Components 

- [x] Dummy Page - https://github.com/HackYourFuture-CPH/simply-name.it/issues/44
    - [ ] AddMemberPage - src/client/containers/AddMemberPage/AddMemberPage.Container.js
    - [ ] AddMemberPage - src/client/containers/AddMemberPage/AddMemberPage.Style.css
- [x] Arrow Button - https://github.com/HackYourFuture-CPH/simply-name.it/issues/4
- [ ] Title    
- [x] Input - https://github.com/HackYourFuture-CPH/simply-name.it/issues/9 
- [x] Button - https://github.com/HackYourFuture-CPH/simply-name.it/issues/2 (probably needs some adaptation)

#### -> Endpoints
- [x] Endpoint to retrieve the list of all the registered users - https://github.com/HackYourFuture-CPH/simply-name.it/issues/47
- [x] Endpoint to search for a user - https://github.com/HackYourFuture-CPH/simply-name.it/issues/79
- [ ] Endpoint to add a member to the board - https://github.com/HackYourFuture-CPH/simply-name.it/issues/80
