### ISSUE TITLE
Fullstack: CreateBoardPage

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/simply-name.it#84]
## User story

**Who:** **As a** User 
**What:** **I want to**  able to create a new Board using the CreateBoard Page and naturally become the Owner of that same Board
**Why:** **so that I can**  ask others to help me with a decision I want to take.

## Acceptance criteria

The page should look like the one below:
<img width="270" alt="Screenshot 2021-07-30 at 18 31 57" src="https://user-images.githubusercontent.com/6642037/127684135-5c8094cf-28e4-4393-b758-ea8f59ef85d7.png">

#### -> React Containers and Components 

- [x] Dummy Page - https://github.com/HackYourFuture-CPH/simply-name.it/issues/44
    - [ ] CreateBoardPage - src/client/containers/CreateBoardPage/CreateBoardPage.Container.js
    - [ ] CreateBoardPage - src/client/containers/CreateBoardPage/CreateBoardPage.Style.css
- [x] Arrow Button - https://github.com/HackYourFuture-CPH/simply-name.it/issues/4 (it should link to ProfilePage)
- [ ] Title
- [x] Input - https://github.com/HackYourFuture-CPH/simply-name.it/issues/9 
- [ ] DatePicker for Datetime using the native browser implementation - check here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local (For now ignore the calendar button in purple)
- [ ] Dropzone component - https://github.com/HackYourFuture-CPH/simply-name.it/issues/83
- [x] Buttons for Add members, Reset and Create - https://github.com/HackYourFuture-CPH/simply-name.it/issues/2 (probably needs some adaptation)

#### -> Endpoints
- [x] Endpoint to add a new board - https://github.com/HackYourFuture-CPH/simply-name.it/issues/67
