### ISSUE TITLE
Fullstack: ProfilePage

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/simply-name.it#89]
## User story

**Who:** **As a** User
**What:** **I want to** be able see the my Profile Page 
**Why:** **so that I can**  have an overview of the Board that I joined and the ones I created, also the have access to create a new Board, delete and edit boards and to Logout.

## Acceptance criteria

The Profile Page should look like this:

**My Boards**
<img width="440" alt="Screenshot 2021-07-30 at 20 54 44" src="https://user-images.githubusercontent.com/6642037/127699185-d5853931-c85f-4c78-9c32-c9bee1c37995.png"> 

**Joined Boards**
<img width="152" alt="Screenshot 2021-07-30 at 21 02 04" src="https://user-images.githubusercontent.com/6642037/127699952-d73f0be1-ace4-498b-b697-430efd122b98.png">

**Logout and Modal View to Board Deletion**
<img width="316" alt="Screenshot 2021-07-30 at 20 55 02" src="https://user-images.githubusercontent.com/6642037/127699177-86bfd277-75b1-4002-b952-863418b57f7f.png">

#### -> React Containers and Components 
- [x] Dummy Page - https://github.com/HackYourFuture-CPH/simply-name.it/issues/44
    - [x] ProfilePage - src/client/containers/ProfilePage/ProfilePage.Container.js
    - [x] ProfilePage - src/client/containers/ProfilePage/ProfilePage.Style.css
- [x] Header - https://github.com/HackYourFuture-CPH/simply-name.it/issues/15
- [x] Profile Picture #159
- [x] Arrow #160
- [x] Tab Separators
- [x] Board Banners
- [x]  Modal View to Delete a Board #189 
- [ ] Creat New Board #212 
- [ ] Edit board #86 

#### -> Endpoints
- [x] Endpoint to retrieve the data of a specific user - https://github.com/HackYourFuture-CPH/simply-name.it/issues/48
- [x] Endpoint to retrieve the list of the boards a specific user joined - https://github.com/HackYourFuture-CPH/simply-name.it/issues/38
- [x] Endpoint to retrieve the list of the boards a specific user created - https://github.com/HackYourFuture-CPH/simply-name.it/issues/40

**Comment by islam-fawzy25** [comment]
@dpfernandes  for Tap saparator and Board banners 
i have to create new issues and PRs ??

**Comment by dpfernandes** [comment]
@islam-fawzy25 the questions can be: 

Is there anyone else in need of that or are tab and banners just for the Profile page?

Is this ProfilePage very complex and should we break it down in small PRs?

I will let you decide that @islam-fawzy25
