### ISSUE TITLE
Extend the BoardPage and Add Candidates

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/simply-name.it#92]
## User story

**Who:** **As a** User Owner of a Board
**What:** **I want to**  be able to add new candidates
**Why:** **so that I can**  make sure that people consider all of the options and rank them accordingly to their preference

## Acceptance criteria

The page should look like this if the user is the Owner of the Board
<img width="470" alt="Screenshot 2021-07-30 at 13 53 02" src="https://user-images.githubusercontent.com/6642037/127649173-86270ffa-c737-43f8-bca9-6db45f7a912b.png">

#### -> React Containers and Components 

- [ ] Extend the Board Page - https://github.com/HackYourFuture-CPH/simply-name.it/issues/74 and add funcionality to Candidate Input - https://github.com/HackYourFuture-CPH/simply-name.it/issues/9         
- [ ] and Add Button -  https://github.com/HackYourFuture-CPH/simply-name.it/issues/2 (probably needs some adaptation)

#### -> Endpoints

- [x] Endpoint to add a new candidate - https://github.com/HackYourFuture-CPH/simply-name.it/issues/91
